import React, { useState, useRef, useEffect } from 'react';

function formatTime(seconds) {
  if (!seconds || isNaN(seconds)) return '00:00';
  const m = Math.floor(seconds / 60).toString().padStart(2, '0');
  const s = Math.floor(seconds % 60).toString().padStart(2, '0');
  return `${m}:${s}`;
}

export default function PodcastPlayer({ audioUrl, metadata, onReset }) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const audioRef = useRef(null);

  useEffect(() => {
    const audio = audioRef.current;
    if (audio) {
      const updateProgress = () => {
        setCurrentTime(audio.currentTime);
        if (audio.duration > 0) {
          setProgress((audio.currentTime / audio.duration) * 100);
        }
      };
      const handleEnded = () => setIsPlaying(false);
      const handleLoadedMetadata = () => {
        setDuration(audio.duration);
      };

      audio.addEventListener('timeupdate', updateProgress);
      audio.addEventListener('ended', handleEnded);
      audio.addEventListener('loadedmetadata', handleLoadedMetadata);

      return () => {
        audio.removeEventListener('timeupdate', updateProgress);
        audio.removeEventListener('ended', handleEnded);
        audio.removeEventListener('loadedmetadata', handleLoadedMetadata);
      };
    }
  }, [audioUrl]);

  const togglePlay = () => {
    if (audioRef.current) {
      if (isPlaying) {
        audioRef.current.pause();
      } else {
        audioRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  return (
    <div className="flex flex-col gap-margin w-full">
      <div className="border border-outline-variant bg-surface-container flex flex-col w-full shadow-2xl">
        <div className="border-b border-outline-variant p-gutter bg-surface-container-high flex justify-between items-center">
          <div className="font-headline-md text-headline-md text-on-surface uppercase truncate flex items-center gap-2">
            <span className="material-symbols-outlined text-primary text-[24px]">podcasts</span>
            {metadata?.sport || 'UNKNOWN SPORT'} <span className="text-outline-variant mx-1">/</span> {metadata?.title || 'GENERATED PODCAST'}
          </div>
          <div className="font-status-code text-status-code text-secondary bg-on-secondary-fixed-variant px-2 py-1 border border-secondary">
            [READY]
          </div>
        </div>
        
        <div className="p-margin flex flex-col gap-margin">
          <p className="font-body-lg text-body-lg text-on-surface-variant border-l-2 border-outline-variant pl-4 py-2">
            {metadata?.overview || 'Audio podcast successfully generated from the provided commentary. This is an overview of the content generated by the AI.'}
          </p>

          <div className="flex flex-col gap-unit border border-outline-variant bg-background p-gutter mt-2">
            <div className="flex items-center gap-gutter">
              <button 
                onClick={togglePlay}
                className="w-14 h-14 border border-outline-variant bg-surface-container-lowest text-on-surface hover:text-primary hover:border-primary flex items-center justify-center transition-colors"
              >
                <span className="material-symbols-outlined text-[32px]">
                  {isPlaying ? 'pause' : 'play_arrow'}
                </span>
              </button>

              <div className="flex-1 flex flex-col gap-2">
                <div className="flex justify-between font-status-code text-status-code text-on-surface-variant">
                  <span>{formatTime(currentTime)}</span>
                  <span>{formatTime(duration)}</span>
                </div>
                <div 
                  className="h-3 w-full border border-outline-variant bg-surface-container cursor-pointer relative"
                  onClick={(e) => {
                    if (audioRef.current && !isNaN(audioRef.current.duration)) {
                      const rect = e.currentTarget.getBoundingClientRect();
                      const x = e.clientX - rect.left;
                      const percentage = x / rect.width;
                      audioRef.current.currentTime = percentage * audioRef.current.duration;
                    }
                  }}
                >
                  <div 
                    className="absolute top-0 left-0 h-full bg-primary transition-all duration-75 ease-linear border-r border-on-surface"
                    style={{ width: `${progress}%` }}
                  ></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="p-gutter border-t border-outline-variant bg-surface-container-lowest flex justify-between items-center gap-unit">
           <button 
            onClick={onReset}
            className="text-on-surface-variant hover:text-on-surface font-label-caps text-label-caps uppercase transition-colors"
          >
            &lt; New Generation
          </button>
          <a 
            href={audioUrl || '#'} 
            download 
            className="border border-outline-variant bg-surface-container hover:border-primary hover:text-primary text-on-surface px-6 py-3 font-label-caps text-label-caps uppercase transition-colors inline-flex items-center gap-2"
          >
            <span className="material-symbols-outlined text-[18px]">download</span>
            Download .WAV
          </a>
        </div>
      </div>
      {/* We use a placeholder audio if audioUrl is not provided so the UI still functions for design viewing */}
      <audio ref={audioRef} src={audioUrl || 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'} className="hidden" preload="metadata" />
    </div>
  );
}
